version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
      - ./_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    healthcheck:
      test: bash -c "</dev/tcp/nginx/8070 && exit 0 || exit 1"
      interval: 3s
      timeout: 30s
      retries: 10
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
      - ./_docker/php-fpm.d/www.conf:/usr/local/etc/www.conf

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=paindetect
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
